name: Deploy Jaspr to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Install Jaspr CLI
        run: dart pub global activate jaspr_cli

      - name: Build
        run: jaspr build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/jaspr

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    runs-on: ubuntu-latest

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4